# Generated by Django 4.0.4 on 2022-05-11 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=15)),
                ('state_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(58)])),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email adress')),
                ('speciality', models.CharField(blank=True, max_length=150)),
                ('grade', models.CharField(blank=True, max_length=200)),
                ('twitter_account', models.URLField(blank=True)),
                ('linkedin_account', models.URLField(blank=True)),
                ('google_scholar_account', models.URLField(blank=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location')),
            ],
            options={
                'ordering': ['joined'],
            },
        ),
    ]
