# Generated by Django 4.0.4 on 2022-05-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='image',
            field=models.ImageField(default='profile_pic/graduated.png', upload_to='profile_pic'),
        ),
    ]
