# Generated by Django 4.0.4 on 2022-05-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_researcher_groups_researcher_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state_name',
            field=models.CharField(max_length=30),
        ),
    ]
