# Generated by Django 4.0.4 on 2022-05-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_researcher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='image',
            field=models.ImageField(default='static/profile_pic/graduated.png', upload_to='profile_pic'),
        ),
    ]
