# Generated by Django 4.0.4 on 2022-05-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_researcher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='location_researchers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location'),
        ),
    ]
