# Generated by Django 4.0.4 on 2022-05-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_researcher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_pic'),
        ),
    ]
