# Generated by Django 4.0.4 on 2022-05-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_researcher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablisment',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='directions_researchers',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='division_researchers',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='etablisment_researchers',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='laboratoire_researchers',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='location_researchers',
        ),
    ]
